import sqlite3
import json
import os
from datetime import datetime

DB_PATH = 'studio_pierrot.db'
OUTPUT_PATH = 'dashboard/data.js'

def get_latest_data():
    """Query warehouse for latest anime metrics"""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    # Query anime data from fact_anime_metrics
    query = '''
    SELECT 
        a.mal_id as id,
        a.title,
        f.score,
        f.members,
        f.favorites,
        f.rank,
        f.rank,
        a.episodes,
        a.type,
        a.status,
        a.start_date as air_date_start
    FROM fact_anime_metrics f
    JOIN dim_anime a ON f.anime_id = a.anime_id
    ORDER BY f.score DESC
    '''
    
    cursor.execute(query)
    rows = cursor.fetchall()
    
    # Convert to list of dicts and fill missing values
    data = []
    for i, row in enumerate(rows, 1):
        item = dict(row)
        # Estimate favorites if missing (approx 1.5% of members)
        if not item['favorites']:
            item['favorites'] = int(item['members'] * 0.015) if item['members'] else 0
        
        # Estimate rank if missing (based on current sort order by score)
        if not item['rank']:
            item['rank'] = i
            
        data.append(item)
        
    conn.close()
    return data

def get_financial_data():
    """Query warehouse for financial/ROI metrics"""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    # Query financial data
    query = '''
    SELECT 
        a.mal_id as id,
        a.title,
        f.tier,
        f.production_budget,
        f.streaming_revenue,
        f.disc_revenue,
        f.merch_revenue,
        f.total_revenue,
        f.profit,
        f.roi,
        f.profit_per_episode,
        a.episodes
    FROM fact_finance f
    JOIN dim_anime a ON f.anime_id = a.anime_id
    ORDER BY f.roi DESC
    '''
    
    cursor.execute(query)
    rows = cursor.fetchall()
    
    # Convert to list of dicts
    financial_data = [dict(row) for row in rows]
    
    conn.close()
    return financial_data

def export_to_js(data, financial_data):
    """Write data to JS file"""
    timestamp = datetime.now().isoformat()
    js_content = f"// Auto-generated by etl/export_to_dashboard.py on {timestamp}\n"
    js_content += f"// Source: SQLite Warehouse ({DB_PATH})\n"
    js_content += f"export const lastUpdated = '{timestamp}';\n"
    js_content += "export const animeData = " + json.dumps(data, indent=2) + ";\n"
    js_content += "export const financialData = " + json.dumps(financial_data, indent=2) + ";\n"
    
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"✅ Exported {len(data)} records to {OUTPUT_PATH}")

if __name__ == '__main__':
    if not os.path.exists(DB_PATH):
        print(f"❌ Database not found: {DB_PATH}")
    else:
        data = get_latest_data()
        financial_data = get_financial_data()
        if data:
            export_to_js(data, financial_data)
            print(f"✅ Also exported {len(financial_data)} financial records")
