import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// List of Studio Pierrot Anime IDs (MyAnimeList IDs)
// Naruto: 20, Naruto Shippuden: 1735, Boruto: 34566
// Bleach: 269, Bleach TYBW: 41467
// Tokyo Ghoul: 22319, Tokyo Ghoul Root A: 27899
// Black Clover: 34572
// Yu Yu Hakusho: 392
// Great Teacher Onizuka: 245
// Kingdom: 12031
// Akudama Drive: 41433
const ANIME_IDS = [20, 1735, 34566, 269, 41467, 22319, 27899, 34572, 392, 245, 12031, 41433];

const DELAY_MS = 1000; // Jikan API rate limit is roughly 3 requests/second, being safe with 1s

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function fetchAnimeData(id) {
    try {
        const response = await fetch(`https://api.jikan.moe/v4/anime/${id}`);
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        return data.data;
    } catch (error) {
        console.error(`Error fetching anime ID ${id}:`, error.message);
        return null;
    }
}

async function runETL() {
    console.log('🚀 Starting ETL Process: Fetching data from Jikan API...');

    const rawData = [];

    for (const id of ANIME_IDS) {
        console.log(`Fetching data for Anime ID: ${id}...`);
        const anime = await fetchAnimeData(id);
        if (anime) {
            rawData.push(anime);
            console.log(`✅ Success: ${anime.title}`);
        }
        await sleep(DELAY_MS);
    }

    // 1. Save Raw Data
    const rawDataPath = path.join(__dirname, '../data/raw_jikan_data.json');
    // Ensure directory exists
    const dataDir = path.dirname(rawDataPath);
    if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
    }
    fs.writeFileSync(rawDataPath, JSON.stringify(rawData, null, 2));
    console.log(`💾 Raw data saved to ${rawDataPath}`);

    // 2. Transform Data for Dashboard
    const processedData = rawData.map(anime => ({
        id: anime.mal_id,
        title: anime.title,
        type: anime.type,
        episodes: anime.episodes,
        status: anime.status,
        score: anime.score,
        scored_by: anime.scored_by,
        rank: anime.rank,
        popularity: anime.popularity,
        members: anime.members,
        favorites: anime.favorites,
        rating: anime.rating,
        aired_from: anime.aired.from,
        image_url: anime.images.jpg.image_url,
        url: anime.url
    }));

    // 3. Save as JS file for direct frontend import
    const dashboardDataPath = path.join(__dirname, '../dashboard/data.js');
    const fileContent = `// Auto-generated by etl/fetch_data.js on ${new Date().toISOString()}
export const animeData = ${JSON.stringify(processedData, null, 2)};
`;
    fs.writeFileSync(dashboardDataPath, fileContent);
    console.log(`💾 Dashboard data saved to ${dashboardDataPath}`);
    console.log('✨ ETL Process Completed Successfully!');
}

runETL();
